version: '{build}'
image: Visual Studio 2017

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

environment:
  BuildNumber: '%APPVEYOR_BUILD_NUMBER%'
  RepositoryBranch: '%APPVEYOR_REPO_BRANCH%'
  RepositoryCommit: '%APPVEYOR_REPO_COMMIT%'

build_script:
- cmd: dotnet build

test:
  assemblies:
    only:
    - tests/**/*.Tests.dll

after_test:
- cmd: dotnet pack -o ../../packages

artifacts:
- path: packages/*.nupkg
  name: Packages

deploy:
- provider: NuGet
  api_key:
    secure: p4B3TD0THQhpN9Y05bHz0+NqJszuMGSZ2ONH2wNhHW4DJEBxp0cSw8zMJE2vH2f+
  skip_symbols: true
  artifact: Packages
  on:
    branch: master