version: '{build}'
image: Ubuntu2004

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

environment:
  BuildNumber: '%APPVEYOR_BUILD_NUMBER%'
  RepositoryBranch: '%APPVEYOR_REPO_BRANCH%'
  RepositoryCommit: '%APPVEYOR_REPO_COMMIT%'

build_script:
  - sh: dotnet pack --output ./packages

artifacts:
- path: packages/*.nupkg
  name: packages

deploy:
- provider: NuGet
  api_key:
    secure: kjhKEgtGi26pGBlQnvDdH1nv/Ijyf3+OvyqSUvwd5KjJsg7xLQ1iSeDemGRE6g1m
  skip_symbols: true
  artifact: packages
  on:
    branch: master